import { useMemo, useState } from 'react';
import { Button, Empty, Form, Input, List, Modal, Skeleton, Space, Table, Tag, Upload, message } from 'antd';
import { FileCheck2, FileText, GraduationCap, Package, Paperclip, UploadCloud, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import dayjs from 'dayjs';
import { confirmProductTraining, getMyProductDocuments, getProductDocumentVersionDetail, getProductTrainingConfirmation, markProductDocumentViewed } from '../../api/product.api';
import FileViewerButton from '../../components/FileViewerButton';
import FileDownloadButton from '../../components/FileDownloadButton';
import StatusBadge from '../../components/StatusBadge';
import { useAuth } from '../../auth/AuthProvider';

const allowedExtensions=['.pdf','.jpg','.jpeg','.png','.doc','.docx','.xls','.xlsx'];
const formatDate=value=>value?dayjs(value).format('DD/MM/YYYY'):'—';

export default function MyProductDocumentsPage() {
  const qc=useQueryClient(); const {hasPermission}=useAuth();
  const [selectedProductId,setSelectedProductId]=useState(null); const [selectedVersionId,setSelectedVersionId]=useState(null);
  const [trainingOpen,setTrainingOpen]=useState(false); const [evidenceOpen,setEvidenceOpen]=useState(false); const [fileList,setFileList]=useState([]); const [form]=Form.useForm();
  const query=useQuery({queryKey:['my-product-documents'],queryFn:()=>getMyProductDocuments({page:1,pageSize:500})});
  const rows=query.data||[];
  const products=useMemo(()=>Object.values(rows.reduce((acc,row)=>{const item=acc[row.ProductId]||{...row,documents:[]};item.documents.push(row);acc[row.ProductId]=item;return acc;},{})),[rows]);
  const selected=products.find(item=>item.ProductId===selectedProductId)||null;
  const selectedDocument=selected?.documents.find(item=>item.DocumentVersionId===selectedVersionId)||selected?.documents[0]||null;
  const version=useQuery({queryKey:['product-document-version',selectedDocument?.DocumentVersionId],queryFn:()=>getProductDocumentVersionDetail(selectedDocument.DocumentVersionId),enabled:Boolean(selectedDocument?.DocumentVersionId)});
  const training=useQuery({queryKey:['product-training',selectedDocument?.DocumentVersionId],queryFn:()=>getProductTrainingConfirmation(selectedDocument.DocumentVersionId),enabled:Boolean(selectedDocument?.DocumentVersionId&&evidenceOpen)});
  const refresh=()=>{qc.invalidateQueries({queryKey:['my-product-documents']});if(selectedDocument?.DocumentVersionId)qc.invalidateQueries({queryKey:['product-training',selectedDocument.DocumentVersionId]});};
  const viewed=useMutation({mutationFn:markProductDocumentViewed,onSuccess:refresh,onError:error=>message.error(error.response?.data?.message||error.message)});
  const confirmed=useMutation({mutationFn:values=>confirmProductTraining(selectedDocument.DocumentVersionId,{comment:values.comment,files:fileList.map(item=>item.originFileObj||item)}),onSuccess:()=>{message.success('Đã xác nhận đào tạo cho bộ phận');setTrainingOpen(false);setFileList([]);form.resetFields();refresh();},onError:error=>message.error(error.response?.data?.message||error.message)});
  const columns=[{title:'ItemCode',dataIndex:'ItemCode',width:170,render:value=><span className="process-code">{value}</span>},{title:'Tên sản phẩm',dataIndex:'ProductName',render:value=>value||'—'},{title:'Tài liệu',render:(_,row)=>row.documents.length,width:90,align:'center'},{title:'Tiếp nhận',width:150,render:(_,row)=>{const statuses=row.documents.map(item=>item.DeliveryStatus);const status=statuses.every(item=>item==='TRAINED')?'TRAINED':statuses.some(item=>item==='PENDING')?'PENDING':'VIEWED';return <StatusBadge status={status}/>;}}];
  const files=version.data?.files||[];
  return <div className={`process-workspace product-workspace ${selectedProductId?'has-drawer':''}`}><main className="process-main"><div className="process-titlebar"><div><h1>Sản phẩm</h1><p>Tài liệu sản phẩm được gửi tới bộ phận của bạn</p></div></div><section className="process-table-card"><Table className="process-table" rowKey="ProductId" loading={query.isLoading} dataSource={products} columns={columns} pagination={{pageSize:15}} locale={{emptyText:<Empty description="Bộ phận chưa nhận tài liệu sản phẩm nào"/>}} rowClassName={row=>row.ProductId===selectedProductId?'selected-process-row':''} onRow={row=>({onClick:()=>{setSelectedProductId(row.ProductId);setSelectedVersionId(row.documents[0]?.DocumentVersionId);},style:{cursor:'pointer'}})}/></section></main>
  {selectedProductId&&<aside className="process-drawer"><div className="drawer-header"><div className="drawer-header-copy"><span>Chi tiết sản phẩm</span><strong>{selected?.ItemCode}</strong></div><Button type="text" icon={<X size={20}/>} onClick={()=>setSelectedProductId(null)}/></div>{version.isLoading?<div className="drawer-loading"><Skeleton active/></div>:<><div className="drawer-section product-info-list"><div className="drawer-section-title"><Package size={16}/> Tài liệu đang áp dụng</div>{selected?.documents.map(item=><button type="button" className={`product-user-document ${item.DocumentVersionId===selectedDocument?.DocumentVersionId?'is-selected':''}`} key={item.DocumentVersionId} onClick={()=>setSelectedVersionId(item.DocumentVersionId)}><span><strong>{item.DocumentTypeName}</strong><small>{item.DocumentName} · Phiên bản {item.VersionCode} · {formatDate(item.EffectiveDate)}</small></span><StatusBadge status={item.DeliveryStatus}/></button>)}</div>
  {selectedDocument&&<><div className="drawer-section drawer-file-section"><div className="drawer-section-title"><FileText size={16}/> File phiên bản</div>{files.map(file=><div className="drawer-file-row" key={file.FileId}><div><strong>{file.OriginalName}</strong><span>{file.FileRole}</span></div><Space><FileViewerButton file={file} label="Xem" onOpened={()=>viewed.mutateAsync(selectedDocument.DocumentVersionId)}/><FileDownloadButton file={file} label="Tải"/></Space></div>)}{!files.length&&<Empty description="Phiên bản chưa có file"/>}</div><div className="drawer-actions">{selectedDocument.DeliveryStatus==='VIEWED'&&hasPermission('DOCUMENT_TRAINING_CONFIRM')&&<Button type="primary" icon={<GraduationCap size={16}/>} onClick={()=>setTrainingOpen(true)}>Xác nhận đã đào tạo</Button>}{selectedDocument.DeliveryStatus==='TRAINED'&&<Button icon={<FileCheck2 size={16}/>} onClick={()=>setEvidenceOpen(true)}>Minh chứng ({selectedDocument.EvidenceCount||0})</Button>}</div></>}</>}</aside>}
  <Modal title={`Xác nhận đào tạo · ${selected?.ItemCode||''}`} open={trainingOpen} onCancel={()=>{setTrainingOpen(false);setFileList([]);}} onOk={()=>form.submit()} okText="Xác nhận" confirmLoading={confirmed.isPending} okButtonProps={{disabled:!fileList.length}}><Form form={form} layout="vertical" onFinish={confirmed.mutate}><Form.Item label="Biên bản / minh chứng" required><Upload.Dragger multiple maxCount={10} fileList={fileList} beforeUpload={file=>{const ext=`.${file.name.split('.').pop()?.toLowerCase()}`;if(!allowedExtensions.includes(ext)||file.size>50*1024*1024){message.error(`${file.name}: định dạng hoặc dung lượng không hợp lệ.`);return Upload.LIST_IGNORE;}return false;}} onChange={({fileList:next})=>setFileList(next)}><UploadCloud size={32}/><p>Chọn tối đa 10 file, 50 MB/file</p></Upload.Dragger></Form.Item><Form.Item name="comment" label="Ghi chú"><Input.TextArea rows={3} maxLength={1000}/></Form.Item></Form></Modal>
  <Modal title="Minh chứng đào tạo" open={evidenceOpen} onCancel={()=>setEvidenceOpen(false)} footer={null}><List loading={training.isLoading} dataSource={training.data?.evidence||[]} locale={{emptyText:<Empty description="Không có minh chứng"/>}} renderItem={file=><List.Item actions={[<FileViewerButton key="view" file={file} label="Xem"/>,<FileDownloadButton key="download" file={file} label="Tải"/>]}><List.Item.Meta avatar={<Paperclip size={18}/>} title={file.OriginalName}/></List.Item>}/></Modal></div>;
}
