import { useMemo, useState } from 'react';
import { Button, DatePicker, Empty, Form, Input, Modal, Popconfirm, Select, Skeleton, Space, Table, Tabs, Tag, message } from 'antd';
import { Boxes, Clock3, Edit3, FilePlus2, FileText, History, Link2, Package, Plus, RotateCcw, Search, Trash2, Upload, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import dayjs from 'dayjs';
import { useAuth } from '../../auth/AuthProvider';
import { getDocumentTypes } from '../../api/master.api';
import {
  createProductDocument, createProductDocumentVersion, deleteProduct, deleteProductDocument, deleteProductDocumentVersion,
  getProductDetail, getProductDocumentDetail, getProductDocuments, getProductDocumentVersionDetail, getProducts,
  mapProductDocument, restoreProduct, restoreProductDocument, restoreProductDocumentVersion, unmapProductDocument,
  updateProduct, updateProductDocument, updateProductDocumentVersion, upsertProduct
} from '../../api/product.api';
import DepartmentSelect from '../../components/DepartmentSelect';
import FileUploader from '../../components/FileUploader';
import FileViewerButton from '../../components/FileViewerButton';
import FileDownloadButton from '../../components/FileDownloadButton';
import StatusBadge from '../../components/StatusBadge';

const formatDate = value => value ? dayjs(value).format('DD/MM/YYYY') : '—';
const toDate = value => value ? dayjs(value) : null;
const masterStatuses = [{value:'ACTIVE',label:'Đang hoạt động'},{value:'INACTIVE',label:'Ngừng hoạt động'},{value:'ARCHIVED',label:'Đã lưu trữ'}];

function InfoRow({ label, children }) {
  return <div className="product-info-row"><span>{label}</span><strong>{children || '—'}</strong></div>;
}

function DeletedModeFilter({ value, onChange }) {
  return <div className="filter-field"><label>Dữ liệu</label><Select value={value} onChange={onChange} options={[{value:'ACTIVE',label:'Đang sử dụng'},{value:'DELETED',label:'Đã xóa'},{value:'ALL',label:'Tất cả'}]} /></div>;
}

function ProductMasterWorkspace() {
  const qc=useQueryClient();
  const {hasPermission,hasRole}=useAuth();
  const isAdmin=hasRole('ADMIN');
  const [keyword,setKeyword]=useState('');
  const [deletedMode,setDeletedMode]=useState('ACTIVE');
  const [selectedId,setSelectedId]=useState(null);
  const [createOpen,setCreateOpen]=useState(false);
  const [editOpen,setEditOpen]=useState(false);
  const [createForm]=Form.useForm();
  const [editForm]=Form.useForm();
  const list=useQuery({queryKey:['products',keyword,deletedMode],queryFn:()=>getProducts({keyword:keyword||undefined,deletedMode,page:1,pageSize:500})});
  const detail=useQuery({queryKey:['product',selectedId],queryFn:()=>getProductDetail(selectedId),enabled:Boolean(selectedId)});
  const product=detail.data?.product;
  const documents=detail.data?.documents||[];
  const refresh=()=>{qc.invalidateQueries({queryKey:['products']});if(selectedId)qc.invalidateQueries({queryKey:['product',selectedId]});};
  const createMutation=useMutation({mutationFn:upsertProduct,onSuccess:data=>{message.success('Đã tạo sản phẩm');setCreateOpen(false);createForm.resetFields();setSelectedId(data.Id);refresh();},onError:e=>message.error(e.response?.data?.message||e.message)});
  const updateMutation=useMutation({mutationFn:values=>updateProduct(selectedId,values),onSuccess:()=>{message.success('Đã cập nhật sản phẩm');setEditOpen(false);refresh();},onError:e=>message.error(e.response?.data?.message||e.message)});
  const deleteMutation=useMutation({mutationFn:()=>deleteProduct(selectedId),onSuccess:()=>{message.success('Đã xóa mềm sản phẩm');setSelectedId(null);refresh();},onError:e=>message.error(e.response?.data?.message||e.message)});
  const restoreMutation=useMutation({mutationFn:()=>restoreProduct(selectedId),onSuccess:()=>{message.success('Đã khôi phục sản phẩm');refresh();},onError:e=>message.error(e.response?.data?.message||e.message)});
  const openEdit=()=>{editForm.setFieldsValue({itemCode:product.ItemCode,productName:product.ProductName,modelCode:product.ModelCode,customerCode:product.CustomerCode,customerName:product.CustomerName,productLine:product.ProductLine,category:product.Category});setEditOpen(true);};
  const productFields=readOnlyCode=><><Form.Item name="itemCode" label="ItemCode" rules={[{required:true,whitespace:true}]}><Input disabled={readOnlyCode} maxLength={100}/></Form.Item><Form.Item name="productName" label="Tên sản phẩm"><Input maxLength={255}/></Form.Item><div className="form-grid-2"><Form.Item name="modelCode" label="Model"><Input maxLength={100}/></Form.Item><Form.Item name="category" label="Danh mục"><Input maxLength={100}/></Form.Item></div><div className="form-grid-2"><Form.Item name="customerCode" label="Mã khách hàng"><Input maxLength={100}/></Form.Item><Form.Item name="customerName" label="Khách hàng"><Input maxLength={200}/></Form.Item></div><Form.Item name="productLine" label="Dòng sản phẩm"><Input maxLength={100}/></Form.Item></>;
  const columns=[{title:'ItemCode',dataIndex:'ItemCode',width:150,render:v=><span className="process-code">{v}</span>},{title:'Tên sản phẩm',dataIndex:'ProductName',render:v=>v||'—'},{title:'Model',dataIndex:'ModelCode',width:130,render:v=>v||'—'},{title:'Khách hàng',dataIndex:'CustomerName',width:170,render:v=>v||'—'},{title:'Tài liệu',dataIndex:'DocumentCount',width:80,align:'center'},{title:'Trạng thái',key:'status',width:120,render:(_,row)=><StatusBadge status={row.IsDeleted?'DELETED':row.IsActive?'ACTIVE':'INACTIVE'}/>}];
  return <div className={`process-workspace product-workspace ${selectedId?'has-drawer':''}`}>
    <main className="process-main"><div className="process-titlebar"><div><h1>Sản phẩm</h1><p>Quản lý ItemCode và thông tin sản phẩm</p></div>{hasPermission('PRODUCT_MANAGE')&&<Button type="primary" size="large" icon={<Plus size={18}/>} onClick={()=>setCreateOpen(true)}>Thêm sản phẩm</Button>}</div>
      <section className="process-table-card"><div className="process-filters product-filters"><div className="filter-field filter-search"><label>Tìm kiếm</label><Input allowClear prefix={<Search size={17}/>} value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="ItemCode, tên hoặc model..."/></div>{isAdmin&&<DeletedModeFilter value={deletedMode} onChange={setDeletedMode}/>}</div>
      <Table className="process-table" rowKey="Id" loading={list.isLoading} dataSource={list.data||[]} columns={columns} pagination={{pageSize:10}} rowClassName={row=>row.Id===selectedId?'selected-process-row':''} onRow={row=>({onClick:()=>setSelectedId(row.Id),style:{cursor:'pointer'}})} locale={{emptyText:<Empty description="Chưa có sản phẩm"/>}}/></section>
    </main>
    {selectedId&&<aside className="process-drawer"><div className="drawer-header"><div className="drawer-header-copy"><span>Chi tiết sản phẩm</span><strong>{product?.ItemCode||'Đang tải...'}</strong></div><Button type="text" icon={<X size={20}/>} onClick={()=>setSelectedId(null)}/></div>{detail.isLoading?<div className="drawer-loading"><Skeleton active/></div>:product?<Tabs className="drawer-tabs" items={[{key:'overview',label:'Tổng quan',children:<><div className="drawer-section product-info-list"><InfoRow label="ItemCode">{product.ItemCode}</InfoRow><InfoRow label="Tên sản phẩm">{product.ProductName}</InfoRow><InfoRow label="Model">{product.ModelCode}</InfoRow><InfoRow label="Khách hàng">{product.CustomerName}</InfoRow><InfoRow label="Dòng sản phẩm">{product.ProductLine}</InfoRow><InfoRow label="Danh mục">{product.Category}</InfoRow><InfoRow label="Trạng thái"><StatusBadge status={product.IsDeleted?'DELETED':product.IsActive?'ACTIVE':'INACTIVE'}/></InfoRow></div><div className="drawer-actions">{product.IsDeleted?isAdmin&&<Button type="primary" icon={<RotateCcw size={16}/>} onClick={()=>restoreMutation.mutate()}>Khôi phục sản phẩm</Button>:<>{hasPermission('PRODUCT_EDIT')&&<Button icon={<Edit3 size={16}/>} onClick={openEdit}>Sửa sản phẩm</Button>}{hasPermission('PRODUCT_DELETE')&&<Popconfirm title="Xóa mềm sản phẩm này?" description="Sản phẩm sẽ bị ẩn nhưng liên kết và lịch sử vẫn được giữ." onConfirm={()=>deleteMutation.mutate()} okText="Xóa" cancelText="Hủy"><Button danger icon={<Trash2 size={16}/>}>Xóa sản phẩm</Button></Popconfirm>}</>}</div></>},{key:'documents',label:<span><FileText size={15}/> Tài liệu ({documents.length})</span>,children:<div className="linked-document-list">{documents.length?documents.map(item=><div className="linked-document-card" key={item.DocumentId}><FileText size={17}/><div><strong>{item.DocumentCode}</strong><span>{item.DocumentName}</span></div><StatusBadge status={item.EffectiveVersionId?'EFFECTIVE':'DRAFT'}/></div>):<Empty description="Chưa liên kết tài liệu"/>}</div>}]} />:<Empty description="Không tìm thấy sản phẩm"/>}</aside>}
    <Modal title="Thêm sản phẩm" open={createOpen} onCancel={()=>setCreateOpen(false)} onOk={()=>createForm.submit()} confirmLoading={createMutation.isPending}><Form form={createForm} layout="vertical" onFinish={createMutation.mutate}>{productFields(false)}</Form></Modal>
    <Modal title={`Sửa sản phẩm · ${product?.ItemCode||''}`} open={editOpen} onCancel={()=>setEditOpen(false)} onOk={()=>editForm.submit()} confirmLoading={updateMutation.isPending}><Form form={editForm} layout="vertical" onFinish={updateMutation.mutate}>{productFields(true)}</Form></Modal>
  </div>;
}

function ProductDocumentWorkspace() {
  const qc=useQueryClient();
  const {hasPermission,hasRole}=useAuth();
  const isAdmin=hasRole('ADMIN');
  const [keyword,setKeyword]=useState('');
  const [deletedMode,setDeletedMode]=useState('ACTIVE');
  const [typeId,setTypeId]=useState();
  const [selectedId,setSelectedId]=useState(null);
  const [selectedVersionId,setSelectedVersionId]=useState(null);
  const [modal,setModal]=useState(null);
  const [masterForm]=Form.useForm(); const [versionForm]=Form.useForm(); const [mapForm]=Form.useForm();
  const types=useQuery({queryKey:['document-types'],queryFn:getDocumentTypes});
  const list=useQuery({queryKey:['product-documents',keyword,typeId,deletedMode],queryFn:()=>getProductDocuments({keyword:keyword||undefined,documentTypeId:typeId,deletedMode,page:1,pageSize:500})});
  const detail=useQuery({queryKey:['product-document',selectedId],queryFn:()=>getProductDocumentDetail(selectedId),enabled:Boolean(selectedId)});
  const document=detail.data?.document; const versions=detail.data?.versions||[]; const products=detail.data?.products||[];
  const currentVersion=useMemo(()=>versions.find(v=>v.Id===selectedVersionId)||versions.find(v=>!v.IsDeleted&&v.Status==='EFFECTIVE')||versions.find(v=>!v.IsDeleted)||versions[0]||null,[versions,selectedVersionId]);
  const versionDetail=useQuery({queryKey:['product-document-version',currentVersion?.Id],queryFn:()=>getProductDocumentVersionDetail(currentVersion.Id),enabled:Boolean(currentVersion?.Id&&!currentVersion?.IsDeleted)});
  const refresh=()=>{qc.invalidateQueries({queryKey:['product-documents']});if(selectedId)qc.invalidateQueries({queryKey:['product-document',selectedId]});if(currentVersion?.Id)qc.invalidateQueries({queryKey:['product-document-version',currentVersion.Id]});};
  const useActionMutation=(fn,success)=>useMutation({mutationFn:fn,onSuccess:data=>{message.success(success);setModal(null);refresh();return data;},onError:e=>message.error(e.response?.data?.message||e.message)});
  const createDoc=useActionMutation(createProductDocument,'Đã tạo tài liệu sản phẩm');
  const editDoc=useActionMutation(values=>updateProductDocument(selectedId,values),'Đã cập nhật tài liệu');
  const removeDoc=useActionMutation(()=>deleteProductDocument(selectedId),'Đã xóa mềm tài liệu');
  const recoverDoc=useActionMutation(()=>restoreProductDocument(selectedId),'Đã khôi phục tài liệu');
  const createVersion=useActionMutation(values=>createProductDocumentVersion(selectedId,{...values,issueDate:values.issueDate?.format('YYYY-MM-DD')||null,effectiveDate:values.effectiveDate?.format('YYYY-MM-DD'),changeSummary:values.changeSummary||null}),'Đã tạo phiên bản');
  const editVersion=useActionMutation(values=>updateProductDocumentVersion(currentVersion.Id,{...values,issueDate:values.issueDate?.format('YYYY-MM-DD')||null,effectiveDate:values.effectiveDate?.format('YYYY-MM-DD'),expiryDate:values.expiryDate?.format('YYYY-MM-DD')||null}),'Đã cập nhật phiên bản');
  const removeVersion=useActionMutation(id=>deleteProductDocumentVersion(id),'Đã xóa mềm phiên bản');
  const recoverVersion=useActionMutation(id=>restoreProductDocumentVersion(id),'Đã khôi phục phiên bản');
  const mapMutation=useActionMutation(values=>mapProductDocument(selectedId,{itemCode:values.itemCode,applicableFrom:values.applicableFrom?.format('YYYY-MM-DD')||null}),'Đã liên kết ItemCode');
  const unmapMutation=useActionMutation(itemCode=>unmapProductDocument(selectedId,itemCode),'Đã kết thúc liên kết ItemCode');
  const openMaster=(modeName)=>{masterForm.setFieldsValue(modeName==='edit'?{documentCode:document.DocumentCode,documentName:document.DocumentName,documentTypeId:document.DocumentTypeId,ownerDepartmentId:document.OwnerDepartmentId,status:document.Status}:{status:'ACTIVE'});setModal(modeName);};
  const openVersion=(modeName,item)=>{if(item)setSelectedVersionId(item.Id);versionForm.setFieldsValue(modeName==='editVersion'?{versionCode:item.VersionCode,issueDate:toDate(item.IssueDate),effectiveDate:toDate(item.EffectiveDate),expiryDate:toDate(item.ExpiryDate),changeSummary:item.ChangeSummary}:{issueDate:dayjs(),effectiveDate:dayjs()});setModal(modeName);};
  const masterFields=<><Form.Item name="documentCode" label="Mã tài liệu" rules={[{required:true,whitespace:true}]}><Input disabled={modal==='edit'} maxLength={100}/></Form.Item><Form.Item name="documentName" label="Tên tài liệu" rules={[{required:true,whitespace:true}]}><Input maxLength={255}/></Form.Item><Form.Item name="documentTypeId" label="Loại tài liệu" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(types.data||[]).map(x=>({value:x.Id,label:`${x.Code} · ${x.Name}`}))}/></Form.Item><Form.Item name="ownerDepartmentId" label="Bộ phận ban hành"><DepartmentSelect allowClear/></Form.Item>{modal==='edit'&&<Form.Item name="status" label="Trạng thái"><Select options={masterStatuses}/></Form.Item>}</>;
  const versionFields=<><Form.Item name="versionCode" label="Mã phiên bản" rules={[{required:true,whitespace:true}]}><Input maxLength={50}/></Form.Item><div className="form-grid-2"><Form.Item name="issueDate" label="Ngày ban hành"><DatePicker format="DD/MM/YYYY" style={{width:'100%'}}/></Form.Item><Form.Item name="effectiveDate" label="Ngày hiệu lực" rules={[{required:true}]}><DatePicker format="DD/MM/YYYY" style={{width:'100%'}}/></Form.Item></div>{modal==='editVersion'&&<Form.Item name="expiryDate" label="Ngày hết hạn"><DatePicker format="DD/MM/YYYY" style={{width:'100%'}}/></Form.Item>}<Form.Item name="changeSummary" label="Nội dung thay đổi"><Input.TextArea rows={4} maxLength={1000}/></Form.Item></>;
  const columns=[{title:'Mã tài liệu',dataIndex:'DocumentCode',width:145,render:v=><span className="process-code">{v}</span>},{title:'Tên tài liệu',dataIndex:'DocumentName'},{title:'Loại',dataIndex:'DocumentTypeName',width:150},{title:'ItemCode',dataIndex:'ItemCodeCount',width:80,align:'center'},{title:'Phiên bản',dataIndex:'EffectiveVersionCode',width:95,render:v=>v||'—'},{title:'Trạng thái',width:120,render:(_,row)=><StatusBadge status={row.IsDeleted?'DELETED':row.Status}/>}];
  const overview=<><div className="drawer-section product-info-list"><InfoRow label="Mã tài liệu">{document?.DocumentCode}</InfoRow><InfoRow label="Tên tài liệu">{document?.DocumentName}</InfoRow><InfoRow label="Loại">{document?.DocumentTypeName}</InfoRow><InfoRow label="Bộ phận">{document?.OwnerDepartmentName}</InfoRow><InfoRow label="Trạng thái"><StatusBadge status={document?.IsDeleted?'DELETED':document?.Status}/></InfoRow></div><div className="drawer-actions">{document?.IsDeleted?isAdmin&&<Button type="primary" icon={<RotateCcw size={16}/>} onClick={()=>recoverDoc.mutate()}>Khôi phục tài liệu</Button>:<>{hasPermission('PRODUCT_DOCUMENT_EDIT')&&<Button icon={<Edit3 size={16}/>} onClick={()=>openMaster('edit')}>Sửa tài liệu</Button>}{hasPermission('PRODUCT_DOCUMENT_DELETE')&&<Popconfirm title="Xóa mềm tài liệu này?" onConfirm={()=>removeDoc.mutate()} okText="Xóa" cancelText="Hủy"><Button danger icon={<Trash2 size={16}/>}>Xóa tài liệu</Button></Popconfirm>}</>}</div></>;
  const versionTab=<div className="version-timeline">{versions.length?versions.map(item=><div className={`version-card ${item.Id===currentVersion?.Id?'is-active':''} ${item.IsDeleted?'is-deleted':''}`} key={item.Id} onClick={()=>setSelectedVersionId(item.Id)}><span className="version-dot"/><span><strong>Phiên bản {item.VersionCode}</strong><small>{item.IsDeleted?`Đã xóa ${formatDate(item.DeletedAt)}${item.DeletedByName?` · ${item.DeletedByName}`:''}`:formatDate(item.EffectiveDate)}</small></span><span><StatusBadge status={item.IsDeleted?'DELETED':item.Status}/><span className="version-card-actions" onClick={e=>e.stopPropagation()}>{!document?.IsDeleted&&!item.IsDeleted&&hasPermission('PRODUCT_DOCUMENT_VERSION_EDIT')&&<Button type="link" size="small" onClick={()=>openVersion('editVersion',item)}>Sửa</Button>}{!document?.IsDeleted&&!item.IsDeleted&&hasPermission('PRODUCT_DOCUMENT_VERSION_DELETE')&&<Popconfirm title="Xóa mềm phiên bản?" onConfirm={()=>removeVersion.mutate(item.Id)}><Button type="link" size="small" danger>Xóa</Button></Popconfirm>}{!document?.IsDeleted&&item.IsDeleted&&isAdmin&&<Button type="link" size="small" onClick={()=>recoverVersion.mutate(item.Id)}>Khôi phục</Button>}</span></span></div>):<Empty description="Chưa có phiên bản"/>}{!document?.IsDeleted&&hasPermission('DOCUMENT_VERSION_CREATE')&&<Button block icon={<FilePlus2 size={16}/>} onClick={()=>openVersion('createVersion')}>Tạo phiên bản</Button>}{!document?.IsDeleted&&currentVersion&&!currentVersion.IsDeleted&&<div className="product-version-files">{(versionDetail.data?.files||[]).map(file=><div className="drawer-file-row" key={file.FileId}><div><strong>{file.OriginalName}</strong><span>{file.FileRole||'PDF'}</span></div><Space><FileViewerButton file={file} label="Xem"/><FileDownloadButton file={file} label="Tải"/></Space></div>)}{currentVersion.Status==='DRAFT'&&hasPermission('DOCUMENT_FILE_UPLOAD')&&<div className="drawer-upload"><Upload size={16}/><FileUploader productDocumentVersionId={currentVersion.Id} onUploaded={refresh}/></div>}</div>}</div>;
  const productTab=<div className="linked-document-list">{products.map(product=><div className="linked-document-card" key={product.ProductId}><Package size={17}/><div><strong>{product.ItemCode}</strong><span>{product.ProductName||'Không có tên'}</span></div>{hasPermission('PRODUCT_MANAGE')&&<Popconfirm title="Kết thúc liên kết ItemCode này?" onConfirm={()=>unmapMutation.mutate(product.ItemCode)}><Button type="text" danger icon={<X size={15}/>} /></Popconfirm>}</div>)}{!products.length&&<Empty description="Chưa có ItemCode"/>}{!document?.IsDeleted&&hasPermission('PRODUCT_MANAGE')&&<Button block icon={<Link2 size={16}/>} onClick={()=>setModal('map')}>Liên kết ItemCode</Button>}</div>;
  return <div className={`process-workspace product-workspace ${selectedId?'has-drawer':''}`}><main className="process-main"><div className="process-titlebar"><div><h1>Tài liệu sản phẩm</h1><p>Quản lý tài liệu, ItemCode và phiên bản</p></div>{hasPermission('DOCUMENT_CREATE')&&<Button type="primary" size="large" icon={<Plus size={18}/>} onClick={()=>openMaster('create')}>Tạo tài liệu</Button>}</div><section className="process-table-card"><div className="process-filters product-filters"><div className="filter-field filter-search"><label>Tìm kiếm</label><Input prefix={<Search size={17}/>} allowClear value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Mã hoặc tên tài liệu..."/></div><div className="filter-field"><label>Loại tài liệu</label><Select allowClear value={typeId} onChange={setTypeId} options={(types.data||[]).map(x=>({value:x.Id,label:x.Name}))}/></div>{isAdmin&&<DeletedModeFilter value={deletedMode} onChange={setDeletedMode}/>}</div><Table className="process-table" rowKey="Id" loading={list.isLoading} dataSource={list.data||[]} columns={columns} pagination={{pageSize:10}} rowClassName={row=>row.Id===selectedId?'selected-process-row':''} onRow={row=>({onClick:()=>{setSelectedId(row.Id);setSelectedVersionId(null);},style:{cursor:'pointer'}})} locale={{emptyText:<Empty description="Chưa có tài liệu sản phẩm"/>}}/></section></main>{selectedId&&<aside className="process-drawer"><div className="drawer-header"><div className="drawer-header-copy"><span>Chi tiết tài liệu</span><strong>{document?.DocumentCode||'Đang tải...'}</strong></div><Button type="text" icon={<X size={20}/>} onClick={()=>setSelectedId(null)}/></div>{detail.isLoading?<div className="drawer-loading"><Skeleton active/></div>:document?<Tabs className="drawer-tabs" items={[{key:'overview',label:'Tổng quan',children:overview},{key:'versions',label:<span><History size={15}/> Phiên bản</span>,children:versionTab},{key:'products',label:<span><Boxes size={15}/> ItemCode</span>,children:productTab}]}/>:<Empty description="Không tìm thấy tài liệu"/>}</aside>}
    <Modal title={modal==='edit'?'Sửa tài liệu sản phẩm':'Tạo tài liệu sản phẩm'} open={['create','edit'].includes(modal)} onCancel={()=>setModal(null)} onOk={()=>masterForm.submit()} confirmLoading={createDoc.isPending||editDoc.isPending}><Form form={masterForm} layout="vertical" onFinish={modal==='edit'?editDoc.mutate:createDoc.mutate}>{masterFields}</Form></Modal>
    <Modal title={modal==='editVersion'?'Sửa phiên bản':'Tạo phiên bản'} open={['createVersion','editVersion'].includes(modal)} onCancel={()=>setModal(null)} onOk={()=>versionForm.submit()} confirmLoading={createVersion.isPending||editVersion.isPending}><Form form={versionForm} layout="vertical" onFinish={modal==='editVersion'?editVersion.mutate:createVersion.mutate}>{versionFields}</Form></Modal>
    <Modal title="Liên kết ItemCode" open={modal==='map'} onCancel={()=>setModal(null)} onOk={()=>mapForm.submit()} confirmLoading={mapMutation.isPending}><Form form={mapForm} layout="vertical" onFinish={mapMutation.mutate}><Form.Item name="itemCode" label="ItemCode" rules={[{required:true,whitespace:true}]}><Input maxLength={100}/></Form.Item><Form.Item name="applicableFrom" label="Áp dụng từ"><DatePicker format="DD/MM/YYYY" style={{width:'100%'}}/></Form.Item></Form></Modal>
  </div>;
}

export default function ProductManagementPage() {
  return <div className="product-domain-page"><Tabs className="product-domain-tabs" defaultActiveKey="products" items={[{key:'products',label:<span><Package size={16}/> Sản phẩm</span>,children:<ProductMasterWorkspace/>},{key:'documents',label:<span><FileText size={16}/> Tài liệu sản phẩm</span>,children:<ProductDocumentWorkspace/>}]}/></div>;
}
